### ISSUE TITLE
what about smart casts?

### ISSUE THREAD

**Issue by zhombie** [skydoves/WhatIf#1]

**Comment by skydoves** [comment]
Hi, @zhombie 
Could you explain more details about the smart casts?

**Comment by zhombie** [comment]
As you can see here below, IDE will automatically detect whether the variable is nullable or not within the certain block

https://kotlinlang.org/docs/reference/typecasts.html#smart-casts

**Comment by zhombie** [comment]
It would be great if your library provides smart casts & there would be no need of using !! symbol, in order to use variable in already checked if statement block, for example,

```
val nullableVariable: String? = null

whatIfNot(nullableVariable) {
     nullableVariable -> smart casted
}
```

**Comment by skydoves** [comment]
It is already using the smart casts and you can get a smart casted field via the receiver.

```kotlin
nullableString.whatIfNotNull {
    val length = it.length
    log("$it is not null.")
}
```

You can check more example codes [here](https://github.com/skydoves/WhatIf/blob/master/app/src/main/java/com/skydoves/whatifdemo/MainActivity.kt).
