### ISSUE TITLE
Publish library as JAR

### ISSUE THREAD

**Issue by alex-arana** [skydoves/WhatIf#2]
Currently, *WhatIf* is published to Maven Central as an Android Archive (AAR) library. Can we also publish it as a JAR library?

**Comment by skydoves** [comment]
Hi, I'm cosidering to separate the library to two independent dependencies; whatif and whatif-android.

I will let you know again If the next package is published.
Thank you for your issue :)

**Comment by skydoves** [comment]
@Hi, alex-arana !
In the new version [1.0.6](https://github.com/skydoves/WhatIf/releases) the `whatIf` module can be used in the kotlin project (non-Android project). Thank you for your issue ;)

**Comment by ubarua123** [comment]
I just used the maven version in my backend and excluded the android part. Works perfectly! Good library. Somehow the illusion of not using `if else` gives me a good feeling. 😄
