### ISSUE TITLE
What about KMP support?

### ISSUE THREAD

**Issue by Gizmodo** [skydoves/WhatIf#20]
Do you plan to make IOS/Native targets for Kotlin Multi Platform?

Currently, if I add WhatIf implementation into commonMain section - I've got sync error: 
iosArm64Main: Could not resolve com.github.skydoves:whatif:1.1.4
iosSimulatorArm64Main: Could not resolve com.github.skydoves:whatif:1.1.4.
iosX64Main: Could not resolve com.github.skydoves:whatif:1.1.4.

**Comment by skydoves** [comment]
That's a great idea! It's actually already on my upcoming roadmap.

**Comment by skydoves** [comment]
@Gizmodo, since 1.2.0 it supports KMP 🎉
