### ISSUE TITLE
Unresolved reference in 1.2.0

### ISSUE THREAD

**Issue by Gizmodo** [skydoves/WhatIf#23]
After switching to 1.2.0 I've got an errors:
Unresolved reference 'whatIfNotNull'.
Unresolved reference 'whatIfNotNullOrEmpty'.

Errors appear in Android project and KMP project

**Comment by skydoves** [comment]
Hey @Gizmodo, new version 1.2.1 has been released and now it fixes the issue. Thank you for your reports!
